### ISSUE TITLE
kosu_latestOrders returns []

### ISSUE THREAD

**Issue by gchaincl** [ParadigmFoundation/kosu-monorepo#361]
When calling `kosu_latestOrders` in testnet the response is an empty array

```bash
➜  ~ ws wss://explore-api.kosu.io/jsonrpc
{"jsonrpc":"2.0","id":1,"method":"kosu_latestOrders","params":[0,0]}
{"jsonrpc":"2.0","id":1,"result":[]}
```

The expected output is an array with N latest orders, where N is the `OrdersLimit` consensus param

At the time of writing this, the testnet has 84k total orders

```bash
➜  ~ ws wss://explore-api.kosu.io/jsonrpc
{"jsonrpc":"2.0","id":1,"method":"kosu_totalOrders"}                
{"jsonrpc":"2.0","id":1,"result":84609}
```

**Comment by gchaincl** [comment]
I think that the problem is that the genesis file used by the testnet is not defining the `orders_limit` consensus param. So it's assuming 0, and 0 means keep 0 last orders.
We could change the consensus params and re-try. For this, we need to restart the network.

**Comment by hrharder** [comment]
Of course.... So it's not really a bug! Good stuff.

**Comment by hrharder** [comment]
Feel free to re-open if you think it makes sense @gchaincl .
