### ISSUE TITLE
[go-kosu] Floating point arithmetics non-determinism

### ISSUE THREAD

**Issue by gchaincl** [ParadigmFoundation/kosu-monorepo#47]
# Overview
I'm opening this issue as a place to discuss and understand how to reproduce non-deterministic scenarios when performing arithmetic operations so that we can avoid them to make the State Machine crash.

# Steps to reproduce
### Go
```go
package main

import "fmt"

func main() {
	for _, n := range []int{-3, -2, -1, 0, 1, 2, 3} {
		v := 1e16 + n
		d := v - 1e16
		fmt.Printf("1e16 + %2d = %+v (diff: %d)\n", n, v, d)
	}
}
```
```bash
➜  ~ go run float.go
1e16 + -3 = 9999999999999997 (diff: -3)
1e16 + -2 = 9999999999999998 (diff: -2)
1e16 + -1 = 9999999999999999 (diff: -1)
1e16 +  0 = 10000000000000000 (diff: 0)
1e16 +  1 = 10000000000000001 (diff: 1)
1e16 +  2 = 10000000000000002 (diff: 2)
1e16 +  3 = 10000000000000003 (diff: 3)
```
### Python
```python
for i in [-3,-2,-1,0,1,2,3]:
    v = 1e16 + i
    d = v - 1e16
    print("1e16 + %2d = %f (diff: %d)" %(i, v, d))
```
```bash
➜  ~ python float.py
1e16 + -3 = 9999999999999996.000000 (diff: -4)
1e16 + -2 = 9999999999999998.000000 (diff: -2)
1e16 + -1 = 10000000000000000.000000 (diff: 0)
1e16 +  0 = 10000000000000000.000000 (diff: 0)
1e16 +  1 = 10000000000000000.000000 (diff: 0)
1e16 +  2 = 10000000000000002.000000 (diff: 2)
1e16 +  3 = 10000000000000004.000000 (diff: 4)
```

### Node
```js
[-3,-2,-1,0,1,2,3].forEach(function(n) {
	v = 1e16 + n;
	d = v - 1e16;
	console.log("1e16 + %d = %f (diff: %d)", n, v, d);
})
```
```bash
➜  ~ node float.js
1e16 + -3 = 9999999999999996 (diff: -4)
1e16 + -2 = 9999999999999998 (diff: -2)
1e16 + -1 = 10000000000000000 (diff: 0)
1e16 + 0 = 10000000000000000 (diff: 0)
1e16 + 1 = 10000000000000000 (diff: 0)
1e16 + 2 = 10000000000000002 (diff: 2)
1e16 + 3 = 10000000000000004 (diff: 4)
```

## Expected behavior
The `diff` value should be equal to the value added to `1e16`.

## Current behavior
In some implementations, it differs.

This behavior seems to happen when we use big numbers (1e16). It turns out that _Node_ and _Python_ sacrifice some precision (you can see how `diff` increases by a factor of 2).

**Comment by hrharder** [comment]
Handled as of `go-kosu` v0.1

See:
- Rate limit calculation (no floating points): [source](https://github.com/ParadigmFoundation/kosu-monorepo/blob/master/packages/go-kosu/abci/rebalance.go#L81), [tests](https://github.com/ParadigmFoundation/kosu-monorepo/blob/master/packages/go-kosu/abci/rebalance_test.go#L61)
- Power calculation (no floating points): [source](https://github.com/ParadigmFoundation/kosu-monorepo/blob/689e327e65c0837cd997f6eb8dbec7bbbcdec554/packages/go-kosu/abci/witness.go#L101), Need tests!
- Confirmation threshold update: [source](https://github.com/ParadigmFoundation/kosu-monorepo/blob/master/packages/go-kosu/abci/app.go#L204), [tests](https://github.com/ParadigmFoundation/kosu-monorepo/blob/master/packages/go-kosu/abci/app_test.go#L88)
