### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by gchaincl** [ParadigmFoundation/kosu-monorepo#77]
## Overview
The node implementation handles different processes running concurrently, most of them related to the witness module; Ethereum watchers (blocks and events) and TM subscription. These run in the background and right now we don't have control over their failures, which means that if one of this process fails, we log the error and quit, but the node keeps running. This is probably not the desired behavior.

We need to define what's the expected behavior and implement it.

**Comment by hrharder** [comment]
Closing because most of the referenced topics in the thread have been covered. Separate issues can/should be opened for more specific error handling.
